#PBS -N bwa.shan
#PBS -q blade
#PBS -l nodes=1:ppn=4,mem=10gb
#PBS -o /home/wuq/bin/pbsEO/shan_bwa_sam.o
#PBS -e /home/wuq/bin/pbsEO/shan_bwa_sam.e
#PBS -S /bin/bash

echo `date`
/home/wuq/bin/bwa-0.6.2/bwa samse /home/wuq/shan/psmc/result/bwa/chY /home/wuq/shan/psmc/result/bwa/smallintestine_50_single.sai /home/wuq/shan/psmc/data/smallintestine_50_single.txt  >/home/wuq/shan/psmc/result/bwa/smallintestine_50_single.sam
echo `date`
