#PBS -N samtools.shan
#PBS -q blade
#PBS -l nodes=1:ppn=4,mem=10gb
#PBS -o /home/wuq/bin/pbsEO/shan_samtools_sort.o
#PBS -e /home/wuq/bin/pbsEO/shan_samtools_sort.e
#PBS -S /bin/bash

echo `date`
/home/wuq/bin/samtools-0.0.18/samtools sort -m 10000000000 /home/wuq/shan/psmc/result/samtools/smallintestine_50_single.bam /home/wuq/shan/psmc/result/samtools/smallintestine_50_single.bam.sort
echo `date`
